version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    ports:
      - '8085:80'
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
  php-fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php_container
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www