version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: nginxcomposetest-main
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:latest
    container_name: nginxcomposetest-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d